### PR TITLE
Fix for precision argument

### PR DESCRIPTION
**Pull request by pixelfreak**
Here you go. This is for Issue #2. I added an argument called `isNumInt` because now `prec` is being used differently internally and externally.

I ran the test suite you have and the only thing that failed is the `build#precision` test, which makes sense because the behavior has changed. The test is updated with the `isNumInt` set to `true`.

Please review. Thanks!

### CODE REVIEW

**Comment by defunctzombie** [comment]
Not sure I like adding an isNumInt argument, I feel like the old (from int) api can maybe go away.

Also, when making patches, please follow the coding style of the project :)

I will review the changes and think of the isNumInt argument. My initial thoughts are that it isn't needed and we can just stick with the precision.

**Comment by pixelfreak** [comment]
What do you mean by stick with the precision?

**Comment by defunctzombie** [comment]
I am not sure I see benefit to supporting the old "int" usecase at all I
what I am thinking. At least not in the constructor.

**Comment by pixelfreak** [comment]
I see. Well, let me know when you have decided. Meanwhile, I'll go with what I have for now. Thanks!

**Comment by defunctzombie** [comment]
https://github.com/shtylman/node-num/commit/214d0b4fb6630cd542088b18d02aceddc96abc89

So it seems the main reason the precision/int combination exists is for internal use. I am thinking that a separate method could exist `num.fromInt` or some such that would have a decimal offset field.

**Comment by pixelfreak** [comment]
Sweet! Works for me!

**Pull request closed without merging**
